### ISSUE TITLE
@Auth annotation is not special

### ISSUE THREAD

**Issue by alexcom** [silb/dropwizard-shiro#13]
I was trying to implement parameter injection into resource methods and was using this project as an example when noticed that object I inject is injected regardless of which annotation I put on parameter. For example `@Size(min=0)` for collections or `@NotNull` for objects would do.

Didn't go deeper into code but I didn't find a check that `@Auth` annotation is present on parameter in `TypeFactory#getValueFactory`. Maybe that's the reason...

**Comment by silb** [comment]
My understanding of your question is that your are implementing injection of your own objects unrelated to Shiro and this bundle.

You will have to study the [Jersey / HK2 injection documentation](https://jersey.github.io/documentation/latest/ioc.html).

This project may not be the best example since:

* the injected value is fetched from `SecurityUtils.getSubject()`
* the scope of the HK2 bindings are `javax.inject.Singleton`

**Comment by alexcom** [comment]
I just wanted to point out that with current implementation of this bundle it's possible to inject a Subject without using @Auth. That's probably not what anyone would expect. Not a critical issue of course.

**Comment by silb** [comment]
I see your point now.

In a JAX-RS resource, both of the following lines will result in a `Subject` being injected:
```java
@GET public String get(@javax.validation.constraints.NotNull Subject subject) {}
@GET public String get(@Auth Subject subject) {}
```

**Comment by silb** [comment]
Moving this to <https://github.com/silb/shiro-jersey/issues/12>.
